### ISSUE TITLE
Is there any benefit to having multiple test projects?

### ISSUE THREAD

**Issue by jcespinoza** [JasonGT/NorthwindTraders#104]
@JasonGT I see that you've added unit tests for Domain, Application and UI. Would there be a disadvantage to having them all in the same project, maybe organized in folders or by using a [TestCategory] attribute?

**Comment by JasonGT** [comment]
I think you can go either way, just need to decide what works well for you and your team. I prefer separate projects for large systems, but I could see a single project working well for smaller smaller systems. At a minimum I'd have separate projects for unit / integration / functional test projects, since their cross cutting concerns will be different.
