### ISSUE TITLE
This design is not compatible with Blazor architecture

### ISSUE THREAD

**Issue by aliveli186** [JasonGT/NorthwindTraders#106]
The Blazor has an architecture (Blazor.Shared, Blazor.Server, Blazor.Client) where shared objects are used by both the client and the server.
Those shared objects are Command, Query and ViewModel objects.

In the current design Command and Query objects are in the Application layer.
If Application layer is referenced by the Blazor.Shared it would depend on MediatR, FluentValidation, Mapper, Logger and Persistence layer which seems not right.

1) Command, Query and ViewModel objects should be taken out of Application Layer and could be put inside Domain layer or some new layer like Blazor.Shared. If they are put on Domain layer Mapping functions can be moved there too else will be in Handlers in Application layer.
Validators can be moved to Shared too.
As a result the Shared layer will depend only on MediatR and FluentValidation.
2) Application Layer should only host the Handlers and maybe the Mappers. 

Opinions?

**Comment by cmorgado** [comment]
I think this design is 100% compatible .. 

Think this way: The Blazor is not more than a client to the API ... no logic Business logic should be present ..

I've used this project as blueprint for an Web API, And Razor Pages Backoffice and a Xamarin App that just calls the Web API.

By using swagger on the Web API I have the Client code auto generated for my Xamarin (using  NSwagStudio)
So if I'm correct you'll end up using this client lib on your Blazor Pages project....

**Comment by ValerianHavaux** [comment]
> Share server-side and client-side app logic all written with .NET
[https://docs.microsoft.com/fr-fr/aspnet/core/blazor/?view=aspnetcore-3.0](https://docs.microsoft.com/fr-fr/aspnet/core/blazor/?view=aspnetcore-3.0)

The shared part of blazor's architecture is just sharing logic and is the role of the application Layer. 

If i look samples and examples from [Blazor Community](https://blazor.net/community.html) the application layer clearly plays the same role. 
So I don't quite understand where the problem is. 

For me the Application Layer is egal to Blazor.Shared just move your logic inside application Layer .

**Comment by JasonGT** [comment]
I think @cmorgado and @ValerianHavaux have covered this well. Thanks for your input.
