### ISSUE TITLE
Custom FluentValidation Validator

### ISSUE THREAD

**Issue by lokesh-selvaraj** [JasonGT/NorthwindTraders#118]
Hi Jason, 

Would like to know how would you organize your custom Validator Files using FluentValidation ? Can you please suggest a folder name and its position in the Application Layer 

Thanks,
Lokesh

**Comment by JasonGT** [comment]
Hi Lokesh. I think it is best to locate things that change together in the same folder. Take for example the UpdateCustomer folder (https://github.com/JasonGT/NorthwindTraders/tree/master/Northwind.Application/Customers/Commands/UpdateCustomer). In this folder, I have the UpdateCustomerCommand (including handler) and the UpdateCustomerCommandValidator. If I need to change something related to the UpdateCustomer feature, everything I need is within a single folder. If instead, I move commands, queries, handlers, and validators into their own folders - I would have to navigate to many folders in order to update the UpdateCustomer feature.

Hope this helps. :)
