### ISSUE TITLE
Question: AutoMapper in Commands

### ISSUE THREAD

**Issue by Hameds** [JasonGT/NorthwindTraders#123]
I think we can use `AutoMapper` in commands.  right? for example take a look at handler for `UpdateCustomerCommand` and pay attention to `entity` object (line 44 to 52)

https://github.com/JasonGT/NorthwindTraders/blob/943a7ab24c4ce4c9c1b6b15a7bb1aa4d3451c2fb/Northwind.Application/Customers/Commands/UpdateCustomer/UpdateCustomerCommand.cs#L34-L57

**Comment by JasonGT** [comment]
Hi @Hameds, thanks for the great question.

While you can use it in this case, I prefer not to. I want to be very explicit and obvious about what is going to change as a result of the command.

In addition, I am not expecting to need to reuse this mapping. This is probably the only place I will map from the request to the entity, since ideally, this is the only place I'll be implementing update customer.

Hope this helps. :)
