### ISSUE TITLE
feature request - clean architecture for WebApi project 

### ISSUE THREAD

**Issue by srinivas-n4u** [JasonGT/NorthwindTraders#124]
Hi Jason,

I really like this architecture and i wanted to implement this for my existing projects. But currently I am working on a WebApi project which takes requests from different clients, run some business logic and talks to multiple external RestApi systems to fulfill the request. Can you suggest clean architecture for such projects? I am using ASP .Net Core 2.2, MsSql for this effort. 

Thanks
Srinivas

**Comment by JasonGT** [comment]
Hi, I'd recommend the following:

1. **Treat the external APIs as Infrastructure.** For each external API:
    i. Within Application, add an interface and DTO types required. Core will only interact with this interface and these types.
    ii. Within Infrastructure, add an implementation (for the above interface). Infrastructure is dependent upon Application, so Application won't know anything about this impllementation. The implementation will only accept / return types as defined by the Interface, i.e. those types created in Application.
2. **Use an abstraction with MySql**. Consider implementing the repository / unit of work to interact with MySQL.
3. **Use request DTO types within the API.** Since you have many different clients, you might need to support different API versions in the future. If this is the case, then instead of exposing query and command DTOs to the API, use request DTO types within the API. The API will be responsible for mapping these request DTOs to command / query DTOs.

With the exception of the above suggestions, it's essentially the same approach.

Good luck with your project. :)
