### ISSUE TITLE
Is it possible to F5 run the backend and front end ? 

### ISSUE THREAD

**Issue by punkouter2018** [JasonGT/NorthwindTraders#129]
Or why is having to deploy them separately preferred as you document here ?

**Comment by JasonGT** [comment]
You can launch both together by updating the Configure method within the Startup class as follows:

```
spa.UseAngularCliServer(npmScript: "start");
// spa.UseProxyToSpaDevelopmentServer("http://localhost:4200");
```

Using this approach can result in productivity losses. Since, when making frequent back end changes as it takes up to 10 seconds to relaunch the application after a back end change.

You can learn more here; http://www.codingflow.net/building-single-page-applications-on-asp-net-core-2-2/.
