### ISSUE TITLE
[Question] External service

### ISSUE THREAD

**Issue by jarojasres** [JasonGT/NorthwindTraders#135]
Hello, I am new using this type of architecture and I would like to ask some questions

1. What is the best way to obtain information from an external service?
2. If the connection string is obtained from an external service (Azure Function). How should I affect the command and query handler?

Many thanks

**Comment by rafalschmidt97** [comment]
Hi!
1. Keep external services as infrastructure - interfaces within app and implementation outside. What exactly you wanna know? Best way - you mean http instead of something else like socket or what?
2. Correct me if I'm wrong but you probably can use under development secret file or use Azure Key Vault. On production you will probably keep your secrets in Vault / Env Variables. Then you can access them via IConfiguration. 

I don't have much experience with Azure Serverless so keep that in mind.

**Comment by JasonGT** [comment]
> 1. What is the best way to obtain information from an external service?

- Add an interface and supporting types to Application.
- Add an implementation and mappings to Infrastructure.
- Remember that Infrastructure depends on Application, so you won't have access to the external service types.

> 2. If the connection string is obtained from an external service (Azure Function). How should I affect the command and query handler?

- The devil is in the details, but perhaps you will need to access the connection string as part of dependency injection or follow up on @rafalschmidt97 recommendations.


Happy coding
