### ISSUE TITLE
[Feature request] GraphQL + Token Based (JWT) Authentications & Authorization + ELMAH Integration

### ISSUE THREAD

**Issue by hesamkal2009** [JasonGT/NorthwindTraders#136]
# GraphQL Integration

Hi,
if it is not too much trouble，I would like to ask you to integrate/demonstrate These features  in Northwind Project.

* GraphQL
*  Token Based (JWT) Authentication & Authorization
* ELMAH

Much Appreciated!
Happy Coding.

**Comment by sanhomealex** [comment]
@hesamkal2009, GraphQL can be easily added to presentation project with just few lines of code (take a look into https://docs.microsoft.com/ru-ru/odata/).
OAuth (JWT Authentication and Authorization) requires much more work, since it will require to have IdentityServer up and running as part of Infrastructure. 
On how to integrate ELMAH into presentation project you can refer to https://docs.elmah.io/logging-to-elmah-io-from-microsoft-extensions-logging/. There are also just few lines of code needs to be added.

I am sure that the purpose of this project is to show the concept of DDD implementation using .Net Core without implementation of all possible "around" technologies.

**Comment by hesamkal2009** [comment]
@sanhomealex Thank you for your response, I'll keep that in mind.
Good Luck!
