### ISSUE TITLE
Code review 

### ISSUE THREAD

**Issue by Ashwani44** [JasonGT/NorthwindTraders#137]
Well,this is not a good place to ask for help but if somebody can review my code and suggest me if I am writing my business logic at proper place. I have created a very small demo crud app.

I always gets a confusion when writing a business logic in clean architecture.
Where should I write my heavy business logic in clean architecture ?

 I am creating a small demo project with NpgSql where I have got the scenario to implement strategy pattern for my employee class. I have implemented the functionality but need somebody to review.

**The scenario :** 
Before saving the employee data i need to perform some calculation based on employee salary.
Hence, after the calculation the final salary will be saved with other employee info.

I have created the startegy and calling in my employee handler class.(just befor saving data in db).
But not happy with the implementation. 

Can anybody tell me the best way to implement my startegy ? 

Here is my repo : https://github.com/Ashwani44/CleanArchitectureCodeReview

Thanks.

**Comment by JasonGT** [comment]
Hi @Ashwani44 - I don't have the capacity for a full code review, however after a quick look I would advise that Oersistence should depend on Application, not the other way around. Try to invert that dependency. In the case of NpgSql - maybe you'll need to use a repository. I didn't note Otherwise, it looks like you're off to a good start. Happy coding!

**Comment by Ashwani44** [comment]
Hi Jason,

Thanks for your response.

Ashwani Singh
Software Developer.
