### ISSUE TITLE
What about using localization?

### ISSUE THREAD

**Issue by MohamedRagab10793** [JasonGT/NorthwindTraders#140]

**Comment by rafalschmidt97** [comment]
@MohamedRagab10793 - You've created three issues without any description what's the problem. Come on! I don't wanna be rude but you can google how to add localization to your .Net Core app. Localization what? Templates? 🧐

**Comment by MohamedRagab10793** [comment]
@rafalschmidt97 -first  i'm very sorry . second It's an easy way to ask Google 
but  my question about how we will using localization with clean architecture 
In another way I am asking about a new way to add localization .

**Comment by JasonGT** [comment]
The goal of localization within the context of clean architecture would be to avoid dependencies on any specific localisation framework. This being the case, treat it as any other infrastructure by adding your new `ILocalisationService` interface to Application and then adding an `LocalisationService` implementation to Infrastructure. Since we're talking .NET Core, check out the following resource for your implementation - https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-2.2. With that in place, it would be trivial to add some queries to support localisation within Application. This would be a good start, depending on your specific needs. Good luck.
