### ISSUE TITLE
How would you handle more complex business transactions?

### ISSUE THREAD

**Issue by Luis-Palacios** [JasonGT/NorthwindTraders#143]
Thanks for this example @JasonGT .

I'm struggling to understand how would you handle a more complex business transaction say something like "Process Order" or "Checkout Order", where you could potentially be affecting multiples database tables and you want to do it in an atomic way "Everything success or everything fails" 

Would you create a single command that does everything? if that is the right answer what about the separation of concerns, DRY and Single Responsibility? Let's say that  you want to split the Checkout logic into multiple commands or something else where each handles a different aspect of the logic for example:

```C#

CheckOutOrder(int orderId) {
    // Calling it service because that is what I'm used but it could be a command or whatever.
    orderService.SetOrderAsSomeState(orderId)
    // Assume you handle some sort of inventory or kardex and you need to update
    productService.AdjustProductsQuantity(orderId)
   // Could call more entites related services that does other things on the database 
    .....
   // Finally I want to save everything or nothing since I'm not in favor on using a repository
  // use dbcontext directly but how you share it accross your services or commands?
  // Do you depend on our IoC container to set the dbContext lifetime per Request and that will
  // make all of you commands/services share the same context safely? 
    dbContext.SaveChanges()

    emailService.SendEmailToClient(order)
}
```
I hope you can shed some light on this as I've been reading for days now and still not sure how to handle this type of logic.

Thank you for your time. 
BTW Amazing conference talks!

**Comment by JasonGT** [comment]
Hi Luis, thanks for your feedback and your question. 

Think of the queries and commands as the entry point from presentation to your application. They support a very specific business case, such as Process Order, Checkout Order, or Cancel Order. It would only make sense to separate Checkout Order into multiple commands if these commands are to be invoked separately from presentation. In that case, we would be really talking about multiple business cases - for example, CheckoutCustomerDetailCommand, CheckoutPaymentDetailCommand, and CheckoutSummaryCommand. These are supporting separate business cases that may or may not be invoked in the checkout process. For example, the customer may change their mind.

I like the example you have supplied, this will work well without too much trouble. I typically won't break it into services unless the command / query has become too complex or if I need to reuse logic. In regards to your comments:

> // Finally I want to save everything or nothing since I'm not in favor on using a repository
> // use dbcontext directly but how you share it accross your services or commands?
> // Do you depend on our IoC container to set the dbContext lifetime per Request and that will
> // make all of you commands/services share the same context safely? 

In the example I have provide, the DbContext is already set up to be injection and shared per request.  Since EF Core will provide an inherent transaction across changes, there is not much you need to do. I hope this helps, happy coding.

Sorry I couldn't reply sooner.
