### ISSUE TITLE
Question on transactions in entities

### ISSUE THREAD

**Issue by dsbahr** [JasonGT/NorthwindTraders#155]
Hi, 

First of all thanks for the great example and repo that you have provided. I've been learning a lot from this!

I need to model a SaaS type domain, where multple users can be part of an account (subscription) that have various Plans.

I'm having a hard time figuring out how to handle the use case of creating a new account.

My simplified domain entities look like this so far:

``` csharp
public class Account 
{
    public int Id {get;set;}
}

public class Membership 
{
    public int AccountId {get;set;}
    public int UserId {get;set;}
}

public class User 
{
    public Id {get;set;}
    public string Email {get;set;}

}
```
I also created a `RegisterAccountCommand`  but I'm unsure where to handle the creation of the  new User entity.  Should the User entity be created in the `RegisterAccountComand` handler or how would you go about implementing this and making sure that an account and a user is created in one atomic transaction?

I was also wondering  if a possible approach is to publish an event using Mediatr such as an`AccountRegistrationStartedEvent` after the AccountId has been generated and then handle this somehwere (where would you handle this) and this somewhere should then trigger a `CreateUserCommand` passing the AccountId as a parameter.

If you could provide an example, or some pointers, that would be greatly appreciated. I did look at the closed issues, but wasn't really able to find an answer, so hopefully I didn't overlook a perfect answer to this. 

Thanks in advance!

**Comment by JasonGT** [comment]
Hi @dsbahr.

Consider the commands and queries to be use cases that support some business need. In this case the user case is to register a new account. In order to do so, we must create the account, the user, and the membership. To support this, using Entity Framework Core, update your entities as follows:

``` csharp
    public class Account
    {
        public int Id { get; set; }

        public ICollection<Membership> Memberships { get; set; }
    }

    public class User
    {
        public int Id { get; set; }
        public string Email { get; set; }

        public ICollection<Membership> Memberships { get; set; }
    }

    public class Membership
    {
        public int AccountId { get; set; }
        public int UserId { get; set; }

        public Account Account { get; set; }
        public User User { get; set; }
    }
```
Then ensure that the above is configured as a many-to-many relationship:

``` csharp
    public class AppDbContext : DbContext
    {
        public AppDbContext (DbContextOptions<AppDbContext> options)
            : base(options)
        {
        }

        public DbSet<User> User { get; set; }

        public DbSet<Account> Accounts { get; set; }

        public DbSet<Membership> Memberships { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Membership>()
                .HasKey(m => new { m.AccountId, m.UserId});

            modelBuilder.Entity<Membership>()
                .HasOne(m => m.Account)
                .WithMany(a => a.Memberships)
                .HasForeignKey(m => m.AccountId);

            modelBuilder.Entity<Membership>()
                .HasOne(m => m.User)
                .WithMany(u => u.Memberships)
                .HasForeignKey(m => m.UserId);
        }
    }
```

The above is a sample db context based on your problem domain. You can learn more about many-to-many relationships here; https://docs.microsoft.com/en-us/ef/core/modeling/relationships#many-to-many.

Now that the model is correctly configured we can return to the use case - register a new account. Since, by default, EF Core supports transactions, we can simply create a new account, user, and membership as follows:

``` csharp
        var user = new User
        {
            Email = "john@northwindtraders.com"
        };

        var account = new Account
        {
        };

        var membership = new Membership
        {
            Account = account,
            User = user
        };

        _context.User.Add(user);
        _context.Accounts.Add(account);
        _context.Memberships.Add(membership);

        await _context.SaveChangesAsync();
```

In the above code, all changes up to `SaveChangesAsync` are applied in a single transaction. You can learn more about this here; https://docs.microsoft.com/en-us/ef/core/saving/transactions.

For this use case, this is a nice simple solution.

> I was also wondering  if a possible approach is to publish an event using Mediatr such as an`AccountRegistrationStartedEvent` after the AccountId has been generated and then handle this somehwere (where would you handle this) and this somewhere should then trigger a `CreateUserCommand` passing the AccountId as a parameter.

I don't think we need to go down that path, since we don't need to wait for the AccountId to be generated. However, you can learn more about raising events with MediatR here; https://github.com/jbogard/MediatR/wiki#publishing. This could be useful for sending a user notification email after the register new account command is completed.

It's not a good practice to have queries / commands call other queries / commands. Think of the queries and commands as the high level use cases and entry points to your application. Start with the simplest approach first and if you encounter duplication follow this advice; https://lostechies.com/jimmybogard/2016/12/12/dealing-with-duplication-in-mediatr-handlers/.

I hope this helps, happy coding! :)
