### ISSUE TITLE
Application layer = Business Logic?

### ISSUE THREAD

**Issue by yncardoso** [JasonGT/NorthwindTraders#156]
Hi @JasonGT,

First of all, thanks for sharing this sample application with us. This might sound very basic but I was wondering where should I add the business logic? Let's say we have a payroll system. It needs to calculate the salary of the employees based on working hours, rates, taxes and etc. Where should I put this logic?

Here's my current structure:

**Application**
 - core layer
   - core - entities, dto's and interfaces - including services (e.g IEmployeeService)
   - application - service implementations (e.g EmployeeService - business logic -> calculate salary)
 - infrastructure
   - infrastructure (third parties, identity, etc)
   - persistence (DbContext, repositories, migrations, etc)

Thanks,

Yuri

**Comment by rafalschmidt97** [comment]
Hi @yncardoso,
First of all this repo is based on cqrs (for example AddEmployeeCommand) rather than services (_employeeService.Add()). Of course you can use services but keep that in mind.

With that said it might be hard to decide where to put IEmployeeService and EmployeeService - both are domain logic. In NorthwindTraders approach you don't have this problem because all/most services you just take as infrastructure (like IFacebookService for example - i don't care about implementation). Here you really care about implementation of EmployeeService.

My recommendation? If you haven't started yet consider cqrs and follow this repo. Otherwise:

- Src
  - Common - Common Extensions, Serializers, Utils, Common Exceptions etc.
  - Core
      - Application - Here you keep all your features. As you said your system is services based so I'll keep here both interfaces and implementations. Splitting them to two project **maybe** might be beneficial (but to be honest I don't see any advantage of that).  But sometimes you have for instance IFacebookService which is not a part of your logic so implementation will be in Infrastructure.
      - Domain - DDD (Entities, Enums, Exceptions, Agregates, Extensions etc.)
  - Infrastructure
    - Persistence - if you are using EF then Context, Configurations, Migrations, Database Initializers (Seeding). Super self explanatory.
    - Infrastructure - implementation for infrastructure services (IFacebookService, Cache?, External services [Third parties] etc). Generally - not important crap here.
  - Presentation
    - WebAPI - ASP.NET CORE (program, startup, controllers, hubs, schedulers?, maybe razor templates?, email templates in the worst case etc.) 
- Test
  - Core
    - Application - TDD Application
    - Domain - TDD Domain
  - Integration? Acceptance? - as always it depends

Btw - explore NorthwindTraders even more 💪 It's really cool, scalable approach.

**Comment by yncardoso** [comment]
Hi @rafalschmidt97,

Thanks for your answer, I really appreciate it. I'm slowly migrating/refactoring a personal project and making decisions like this as I go. Northwind Traders is indeed really cool :)

**Comment by JasonGT** [comment]
Hi @yncardoso. Thanks for your feedback. @rafalschmidt97 has covered this really well. Happy coding!
