### ISSUE TITLE
Create persistence command/query

### ISSUE THREAD

**Issue by emadalsous** [JasonGT/NorthwindTraders#165]
First of all, thanks for this clear and efficient Clean Architecture sample and also for the videos. I am working on project that could evolve constantly.

I am wondering how can i separate between the persistence layer and application layer. I feel that INorthwindDbContext in the presentation layer will make this layer depending even though not directly on the persistence (e.g changing DB from SQL to No-SQL will break the application layer).

I thought about using the Repository pattern but i find that whenever i have new query or command i will have to modify an existing Repository class which is against the Open Closed principle if i understand it correctly.

 I am wondering if it would be a good approach to create a second command/query that will be called from the Application layer inside a command handler. The sub-command will be handled by the persistence layer.

For example: 
`    public class UserLoginCommandHandler : IRequestHandler<UserLoginCommand,string>
    {
        public UserLoginCommandHandler()
        {

        }
        public Task<string> Handle(UserLoginCommand request, CancellationToken cancellationToken)
        {
          var result=Mediator.Send<bool>(new UserExistsQuery() { email=request.Email});
            if(result.Result)
            {
                ///var getanotherThing = Mediator.Send<bool>(new DoSomethingQuery() { param });
            }           
        }
    }
}`

The sub-command query handler will be in the persistence layer as the following :
` public class UserExistsQueryHandler: IRequestHandler<UserExistsQuery,bool>
    {
        public UserExistsQueryHandler()
        {

        }
        public Task<string> Handle(UserExistsQueryrequest, CancellationToken cancellationToken)
        {
          //sub query implementation
        }`

Looking forward to hear your advice if you find it a good approach or not to do so.

Best regards,
Emad

**Comment by brendan-ssw** [comment]
Hi, 

I think that a second layer of commands/queries for persistence can be a good approach. Like any case where you add a new layer, you have to weigh up the cost (in developer time) and complexity of adding that layer against the benefits of decoupling.

My advice here would be to make efforts to ensure a clear separation between Application commands/queries that may contain business logic vs Persistence commands/queries that should only handle persistence considerations.

**Comment by JasonGT** [comment]
Hi and thanks for your nice feedback! :smile:

> I thought about using the Repository pattern but i find that whenever i have new query or command i will have to modify an existing Repository class which is against the Open Closed principle if i understand it correctly.

You can create a Repository implementation that allows you to pass queries in, rather than modifying the repository directly to support new queries. Review the [repository pattern](https://deviq.com/repository-pattern/) and [specification pattern](https://deviq.com/specification-pattern/) at DevIQ. With either approach you won't need to modify the repository to support new queries, and changes to add / update / delete are not usually necessary for specific commands.

> I am wondering if it would be a good approach to create a second command/query that will be called from the Application layer inside a command handler. The sub-command will be handled by the persistence layer.

Avoid having requests send requests, it tends to get messy fast. Instead, aim for a one to one mapping between use cases and queries or commands. Common behaviour can be refactored into another class or method, as described in [Dealing with Duplication in MediatR Handlers](https://lostechies.com/jimmybogard/2016/12/12/dealing-with-duplication-in-mediatr-handlers/).

Keep the above in mind and you should achieve a fairly simple solution that meets your requirements. Happy coding!
