### ISSUE TITLE
How do I add children items to an item ?  

### ISSUE THREAD

**Issue by punkouter2018** [JasonGT/NorthwindTraders#169]
I had to break the pattern of having the child collection read only since I am not sure how I am suppose to add children.. Any idea?  The code I used it below

` public class CreateStatFileBasketCommand : IRequest
    {
        public int Id { get; set; }

        public string Notes { get; set; }

        public List<IFormFile> Files { get; set; }

        public int? StatCategoryId { get; set; }

        public class Handler : IRequestHandler<CreateStatFileBasketCommand, Unit>
        {
            private readonly ISrxDbContext _context;
            private readonly IMediator _mediator;

            public Handler(ISrxDbContext context, IMediator mediator)
            {
                _context = context;
                _mediator = mediator;
            }

            public async Task<Unit> Handle(CreateStatFileBasketCommand request,
                CancellationToken cancellationToken)
            {
                //create basket
                StatFileBasket entity = new StatFileBasket
                {
                    StatFileBasketId = request.Id,
                    OwnerId = "todo",
                    Notes = request.Notes,
                    StatCategoryId = request.StatCategoryId
                };

                _context.StatFileBaskets.Add(entity);

                //create items in basket
                foreach (IFormFile ff in request.Files)
                {
                    StatFileItem childEntity = new StatFileItem
                    {
                        StatFileBasketId = entity.StatFileBasketId,
                        Url = ff.FileName
                    };

                    _context.StatFileItems.Add(childEntity);
                }

                await _context.SaveChangesAsync(cancellationToken);

                await _mediator.Publish(new StatFileBasketCreated
                {
                    StatFileBasketId = entity.StatFileBasketId
                }, cancellationToken);

                return Unit.Value;
            }
        }
    }`

**Comment by JasonGT** [comment]
Hey @punkouter2018 - great question, let me explain.

If I had a class Order, with a collection OrderDetails I could define it as follows:

```csharp
public class Order 
{
    public int OrderId { get; set; }
    public ICollection<OrderDetail> OrderDetails { get; set; }
}
```

When using this class, for example when creating a new order, I might implement as follows:

```csharp
var order = new Order();
order.OrderDetails = new List<OrderDetail();
order.Id = 1;
order.OrderDetails.Add(new OrderDetail(...));
```

When updating an order to add order detail, I might implement that as follows:

```csharp
if (order.OrderDetails == null) {
    order.OrderDetails = new List<OrderDetail();
}

order.OrderDetails.Add(new OrderDetail(...));
```

Can you see the repetition? This is just two examples but in a large system that repetition is going to be all over the place. We can easily avoid this if we instead define order as follows:

```csharp
public class Order 
{
    public Order() 
    {
        OrderDetails = new List<OrderDetail>();
    }

    public int OrderId { get; set; }
    public ICollection<OrderDetail> OrderDetails { get; private set; }
}
```
We no longer need to think about or check to see if OrderDetails has been initialised - it has. So now when creating:

```csharp
var order = new Order();
order.Id = 1;
order.OrderDetails.Add(new OrderDetail(...));
```
And when updating:

```csharp
order.OrderDetails.Add(new OrderDetail(...));
```
We don't need to worry about the state of OrderDetails anymore. It's initialised, because that's the convention we have decided to follow. We make it easy to do the right thing, and hard to do the wrong thing.

Just because we have a private setter on OrderDetails does not mean we cannot add child items. It means that we cannot initialise the property of OrderDetails to another value, we can only do that in the constructor. That doesn't stop us from interacting with the value of OrderDetails (the list), so we can add, update, remove, and find list items easily.

Hope this helps.

**Comment by punkouter2018** [comment]
ok great. .this is better.. this and the other git repo are to two patterns I am using for my project. very helpful!  I just get tripped up easily when I do things not in the examples like uploading files as in the other issue

the other

https://github.com/aspnetrun/run-aspnetcore-realworld

`   foreach (IFormFile ff in request.Files)
                {

                    entity.StatFileItems.Add(new StatFileItem
                    {
                        Url = ff.FileName,
                        StatFileBasketId = entity.StatFileBasketId
                    });

                }






                _context.StatFileBaskets.Add(entity);



                ////create items in basket
                //foreach (IFormFile ff in request.Files)
                //{
                //    StatFileItem childEntity = new StatFileItem
                //    {
                //        StatFileBasketId = entity.StatFileBasketId,
                //        Url = ff.FileName
                //    };

                //    _context.StatFileItems.Add(childEntity);
                //}`

**Comment by JasonGT** [comment]
Awesome, glad to help. You should also check out eShopOnWeb; https://github.com/dotnet-architecture/eShopOnWeb/.
