### ISSUE TITLE
I have to create .cs & .cshtml files dynamically/run time, where to code ?

### ISSUE THREAD

**Issue by sudurrani** [JasonGT/NorthwindTraders#170]
In my scenario I am generating .cs and .cshmtl files programmatically I am done with this my test proj now I want to implement with clean architecture where should I place my code will it comes into application layer or instrastructure
System.IO.File is used for file creation while TextWrite is used to append text

**Comment by JasonGT** [comment]
Super tough question to answer without specifics but I'll take a crack anyway. I'm assuming that the generation of these files is tied somehow to the business logic, and logic belongs in Core (Application and Domain). Since we can't have Infrastructure in Core, you can approach as follows:

1. Create Infrastructure services to manage the programmatic generation of .cs and .cshtml files.
1. Create Interfaces to match these services within Application.
1. Infrastructure depends on Application, and thus will implement the new service interfaces.
1. Application logic will work only with the interfaces, and thus remain independent of Infrastructure.

So you see, the logic remains in the Application layer and the file access stays in the Infrastructure layer. 

Hope this helps - happy coding.

**Comment by sudurrani** [comment]
Great answer helped me alot in understanding more the basic flow and how it will work.
Want to explain a bit more the real scenario I'm working on.
Created a user interface where user enters property name and type(string,int etc) and click save button, on back-end I'm generating Entity and strongly typed view.
Source code is available on here https://github.com/sudurrani/ASPCoreDynamics

**Comment by sudurrani** [comment]
![image](https://user-images.githubusercontent.com/14028940/65812118-fe2d9b80-e1db-11e9-8c9f-64610bd1a8bc.png)

**Comment by JasonGT** [comment]
Very welcome, thanks for sharing and good luck with your project.
