### ISSUE TITLE
First run creates database but tables are not generated in SQL Server

### ISSUE THREAD

**Issue by sudurrani** [JasonGT/NorthwindTraders#172]
As I run my project first time it creates sql server database for me but tables are not created though entities are added.
Do I need to run EF commands from Package Manger Console like
Add-Migration SetAnyName
Update-Database

**Comment by punkouter2018** [comment]
I use these in the seed (for development) 

 context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

**Comment by sudurrani** [comment]
But in my case i don't use Seeding

**Comment by JasonGT** [comment]
For Northwind, the Web UI is configured (in Program.cs) as follows;

```csharp
                    var northwindContext = services.GetRequiredService<NorthwindDbContext>();
                    northwindContext.Database.Migrate();

                    var identityContext = services.GetRequiredService<ApplicationDbContext>();
                    identityContext.Database.Migrate();

                    var mediator = services.GetRequiredService<IMediator>();
                    await mediator.Send(new SeedSampleDataCommand(), CancellationToken.None);
```

In summary, it will create the database if it  does not exist, apply migrations related to northwind and identity, then seed the database using the SeedSampleDataCommnad.

You don't need to run any separate commands. If you've encountered issues just try deleting the Northwind database and re-running Web UI. Good luck.

**Comment by sudurrani** [comment]
![Nexawo](https://user-images.githubusercontent.com/14028940/66293311-c8856280-e8ff-11e9-926d-613799137e26.PNG)
Code I have in my proj Program.cs

One more thing if it auto creates tables, then how it can generate thes migrations as show snap from Northwind app
![Northwind](https://user-images.githubusercontent.com/14028940/66293351-dcc95f80-e8ff-11e9-930f-aaec64091f04.PNG)

**Comment by JasonGT** [comment]
The migrations are created at development time using the EF Core CLI; https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet. Specifically with https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet#dotnet-ef-migrations-add.

The DbContext.Database.Migrate will create the database / apply existing migrations as necessary, but it will not automatically create new migrations for domain entity changes.

> As I run my project first time it creates sql server database for me but tables are not created though entities are added.

So, back to your original question.

> Do I need to run EF commands from Package Manger Console like
> Add-Migration SetAnyName

Yes, this is required to add new migrations.

> Update-Database

This is optional. If you don't run it it will happen as part of Database.Migrate. But it worth running, since it provides quick feedback.

**Comment by sudurrani** [comment]
Thanks @JasonGT :)
