### ISSUE TITLE
How to display user name with another list entity and foriegn key concern

### ISSUE THREAD

**Issue by majumajid** [JasonGT/NorthwindTraders#194]
Thank you Mr. @JasonGT  for keeping project update and awesome architecture, 

Here i have case ,

i have Entity called "Customer", When customer added to database, i have Audit column WHO CREATED AND WHEN CREATED (CreatedBy, CreatedOn). 
As per current implementation i am able to save CreatedBy as Current User Id from CurrentUserService.
Well,
Now i need to show list customer in front end with who created.
1) Since i have Id of the user i know who is the user but How it should be implemented ??

2)  How about making UserId as foreign key of another entity ?

Kindly request any experts or @JasonGT  to provide reply with steps.

**Comment by majumajid** [comment]
@Patrick-Ullrich  Do you have any idea ?

**Comment by majumajid** [comment]
@brendan-ssw Do you have any idea ?

**Comment by majumajid** [comment]
Could you guys please help me to sort out this issue ?

**Comment by majumajid** [comment]
Anyone can help me to fix this issue ?
Really stucked

**Comment by Patrick-Ullrich** [comment]
Identity is usually stored in another database. You probably wanna use the UserManager to retrieve info from there. Check out this [SO post](https://stackoverflow.com/questions/53924347/get-user-role-in-entity-framework-using-join-query-in-asp-net-core). Should probably get you on the right track.

UserManager is in the Infrastructure layer.

**Comment by majumajid** [comment]
@Patrick-Ullrich  Noted.
Incase if i want to diplay  who added records, as per my understand i need to join both tables to get user name of who done.
Hope my initial example is correct.

If you have some time, could you please guide #200

**Comment by hannan-m** [comment]
I'm facing the same issue. Since an entity can only be attached to a single context. 

Here are the few solutions I can think of:
1. Create the entity in IdentityDbContext, which violates the architecture and adds the dependency on Identity.

2. Use `RawSQL` or `StoreProcudure`. Create a join between the `User` and `SecondEntity`.  Which is not EF Core code first friendly but gets the job done.

Can anyone think of any other way? If possible please add an example for this behavior.

**Comment by vyliniem** [comment]
Usually our application-database has its own account/profile entity which holds all the application-specific user-properties like email, real name, display name, address etc. There is also a nullable non-fk unique field AuthId which maps to the IdentityUser ID. All other application-entities then refer to this account-entity when needed.

Then we have extended the Identity UserManager and overriden the CreateAsync(IdentityUser user) method so that the application account-entity is created when ever an IdentityUser is created. The override is also used to grant default roles and and to add the account-id into IdentityUser claims. This way you can read the "current account id" directly from the Identity claims without having to resolve it from the database on every request.

Downside is that some properties like email is held in two places, although having a different email for authentication and for example notifications is a perfectly valid consept.

**Comment by majumajid** [comment]
Thank you all for contributions ,
@vyliniem Thank you for giving exact perfect solution. Really appreciate your great effort to explain in proper way. 


Closing issue
