### ISSUE TITLE
Call to Core from Infrastructure Layer?

### ISSUE THREAD

**Issue by larkydoo** [JasonGT/NorthwindTraders#197]
I have a question: If you have a NotificationService in the Infrastructure layer that send emails, and only want to send an email to a user if they have opted in in their profile (which you need to access a CQRS Query to determine), where should you check to make sure the user has opted in: in the Infrastructure Layer or in the business logic layer where the call to the NotificationService was initiated? 

As I see it, the main benefit to calling it in the NotificationService is that you only have to do it once, whereas otherwise you'd have to do it in each location the NotificationService is called. The benefit to calling it in the business logic code is that it's unit testable. My vote is for NOT doing it in the NotificationService but I wanted to check to make sure my understanding is correct. Or is there a better solution than either of these?

Thanks!

**Comment by Patrick-Ullrich** [comment]
Not an expert. But my 2 cents.

Because I do think this is a business rule, it should live in the Application Layer. How about a service within the Notification Service that checks whether the user opted in or not, that then will call the INotificationService implementation from the persistence layer. This way you will still just call 1 method from your Handler.
Something like CompliantNotificationService.notifyUser?

That being said, I think it does open an interesting discussion on whether the Persistence Project can talk to the Infrastructure Project or to take it even further, should a service in the Infrastructure Project be able to call another Infrastructure service? I think you will have to decide that from case to case and will depend on whether the code includes any business logic that should be transferred when you change the external data source.

**Comment by larkydoo** [comment]
Sorry, originally titled this Persistence instead of Infrastructure layer. Doh!

**Comment by larkydoo** [comment]
Let me make sure I'm understanding this. CompliandNotificationService would have a method for each notification type (different parameters/templates for different messages), and before calling the NotificationService in the Infrastructure layer to send the message you would check to make sure notifyUser was true? Kind of like having a border station between the Web App and the Infrastructure layer that manages traffic?

**Comment by Patrick-Ullrich** [comment]
As I see it, it's just a common service, implementing common Business Logic, used within your Application Layer. Yup. 👍

**Comment by larkydoo** [comment]
Thanks!
