### ISSUE TITLE
Handling Exceptions in the Web API layer

### ISSUE THREAD

**Issue by dillorscroft** [JasonGT/NorthwindTraders#22]
What is the preferred approach for handling errors that can not be trapped with Fluent Validation?  Let's say the there's a duplicate entry and it's surfaced in the Command Handler layer...  Or attempting to delete an item that can't be deleted.   Would these always transpire as 500 errors rather than a say a 412 Precondition failed or something similar.  

Just curious.

**Comment by itgoran** [comment]
@dillorscroft 

I'm practicing the following rules (in case of authorization or validation failed):

1. Any authorization broken rules (i.e due to the lack of permission), 401 will be returned,
2. Any validation broken rule (some required field is not filled, some business date is not in the range etc...) 422 will be returned, with a structure containing property or type which has failed and user-friendly message how to fix it,
3. Some internal errors (due to the null exception, for example :)   ), 500 will be returned with a generic message

**Comment by joepb** [comment]
@itgoran Isn't it prefered to use 403 and 401 for the right cases? 
401 Unauthenticated for cases where the user is not properly authenticated (please log on) and
403 Forbidden for cases where the user is authenticated bus not allowed to perform the request (no, you can't)

422 Unprocessable Entity is specific for WebDAV. I'd say 400 Bad Request would be best for any bad request.

500 for unexpected errors seems ok, as long as you log them an figure out how to expect them the next time (if it's due to the request).

**Comment by itgoran** [comment]
@joepb 
Cases 401 and 403 yes, I've written the short description and practice is totally align with what You said.
500 - yes, we logged them into logging repository.

Do you use server-side API to log client side errors for future diagnostics or just display it at client-side?

**Comment by Sp-NNT** [comment]
@dillorscroft Based on this app I do this way https://github.com/Sp-NNT/GoodExceptions, I combined all the errors in one format

**Comment by dillorscroft** [comment]
I understand the status codes, just not sure how best to bubble them up to the presentation layer/api

**Comment by dillorscroft** [comment]
I've spotted where these are set in the CustomExceptionFilterAttribute.   (Works for me!) . Thanks

**Comment by JasonGT** [comment]
Thanks and that's right, the handling is within https://github.com/JasonGT/NorthwindTraders/blob/master/Northwind.WebUI/Filters/CustomExceptionFilter.cs.
