### ISSUE TITLE
Question: What if Presentation Layer is not the end

### ISSUE THREAD

**Issue by SharpNoiZy** [JasonGT/NorthwindTraders#26]
In my company we are a bit insecure about the work with (Micro)Services.

Your Web API is the top end of the chain, but what if this is just something in between?
Real world would be that this Web API will be a Swagger/Swashbuckle Application.

Then you generate (with NSwag Studio for example) a service consumer class for your API.
Then you have a Web Application what uses the API Service Consumer class.

We discussed everything, the current state is to remove our Application Layer and put all the commands into the Web API, because you are exposing all the Commands and Queries with the Web API.

Would you do that also?

The second point is, in that real world example, there are colleagues that say:
"If we generate, based on the Swagger.json our Service Consumer class that will generate it's own model "copies" you don't need the Domain layer anymore, because the consumer can be a non C# client, that  can't use our C# Domain models anyway and if he is a C# application, he can use the generated model from within the Service Consumer".

What do you think about that?

So, there are two layers under review :)

So, what we mean is, something like this:
- Foundation (Common) (Git Repo/Layer)
- FinanceService (Web API Service that access an external SAP SOAP Service for finance stuff, Commands and Queries with BL) (Solution with 3 projects, Git Repo/Layer)
--- FinanceService.SAP (Lib with Commands and Queries to SAP, raw API calls, no BL)
--- FinanceService.Tests
- FinanceService.ServiceConsumer (One generated C# class from swagger.json) (Git Repo/Layer)
- .net core Web UI (Reference to FinanceService.ServiceConsumer) (Git Repo/Layer)

No Domain Layer, no Application Layer, no Infrastructure Layer. Sure, all of them are somewhere in here but not separated.

And sure that only works, if you expose all your functionality with Web API's.

I'm very interested on your opinion.

**Comment by Advanium** [comment]
Correct me if I'm wrong, but the commands and queries were exposed by the application layer.
Web API is just one of many possible front ends to the core (domain + application layer).

If you follow DDD principles, what you might end up with is a Web API for each bounded context. If one of your application needs access to several contexts you could easily provide access via Web API and access them from within the infrastructure layer. Have a look at his YouTube video [around 35:50](https://youtu.be/_lwCVE_XgqI?t=2092).

**Comment by SharpNoiZy** [comment]
Currently we have a Domain and Application layer, yes, plus Service and ServiceConsumer Layer.
But in our opinion this is to much NuGet hell.

Because the Services (Web API's like the FinanceService) are the only consumer of the application layer, why have it seperated?
So, one layer terminated :)

But the Domain is something different, different opinions here.
Like described above, do you Need a Domain layer if all your presentation applications are just working with the ServiceConsumer which contains generated Models? Puh...I don't know.

**Comment by JasonGT** [comment]
> In my company we are a bit insecure about the work with (Micro)Services.
> 
> Your Web API is the top end of the chain, but what if this is just something in between?
> Real world would be that this Web API will be a Swagger/Swashbuckle Application.
> 
> Then you generate (with NSwag Studio for example) a service consumer class for your API.
> Then you have a Web Application what uses the API Service Consumer class.
> 
> We discussed everything, the current state is to remove our Application Layer and put all the commands into the Web API, because you are exposing all the Commands and Queries with the Web API.
> 
> Would you do that also?

You shouldn't put the commands and queries into the Web API layer, since this would cause your solution to be dependent on Web API (Core should not depend on frameworks). Ideally, you want to in a position to switch out the Web API with a different technology in the future. Also, you might want to create a Console app or similar. With the right design, the Console app could depend directly on the Application layer, rather than forcing it to go through the Web API layer.

> The second point is, in that real world example, there are colleagues that say:
"If we generate, based on the Swagger.json our Service Consumer class that will generate it's own model "copies" you don't need the Domain layer anymore, because the consumer can be a non C# client, that can't use our C# Domain models anyway and if he is a C# application, he can use the generated model from within the Service Consumer".

The Domain entities are different to the models exposed by the Application layer. The entities represent the real world objects that have some data and logic. The models represent the input or output for our commands and queries. They serve two distinct purposes. The generated code will not expose and Domain entities, just the models in the application layer. We do this because we need specific types for specific purposes. For example, the Product entity does not contain sufficient information to update a Product. For that we might create an UpdateProductViewModel. This ViewModel would contain the specific product data, the list of categories, the list of suppliers and so on. We still need the Domain layer. The service consumer would not have access to the Domain layer so it's not a question of whether not the client uses C#.

> I'm very interested on your opinion.

For any non-trivial application, recommend keeping the Domain, Application, and Presentation layers. If you want to simplify it, you might consider merging Domain and Application into a single Core layer. I can't imagine anything less that still adheres to the principles of clean architecture.

Hope this helps, good luck.
