### ISSUE TITLE
Can you explain  Configurations section Northwind.Persistence 

### ISSUE THREAD

**Issue by CodeRapp3r** [JasonGT/NorthwindTraders#27]
Can you explain  Configurations section Northwind.Persistence 

please explain what is exact use of that configuration section in project and it look slimier to query validator
in domain layer

**Comment by XzADAE** [comment]
Hello,

It is the configuration for the entity framework (Fluent API). Instead of placing all of that in the modelbuilder, they are in a separate file (it makes the code cleaner and easier to understand and change) and than all those configuration are applied in the moderbuilder with a method that use reflection to get all those files.

You can watch the presentation of this code https://youtu.be/_lwCVE_XgqI?t=1863

Best regards,
ADAE.

**Comment by CodeRapp3r** [comment]
thank you
