### ISSUE TITLE
implementing identity server 4

### ISSUE THREAD

**Issue by CodeRapp3r** [JasonGT/NorthwindTraders#28]
implementing identity server 4
JasonGT i am trying to impliment  identity server 4 in project

i create another Project as Northwid.identityServer  and i have another project  Northwid.WebUi(API)
2)Now I want to Configure and seed  Identityserver4.Entityframework ....(https://identityserver4.readthedocs.io/en/release/quickstarts/8_entity_framework.html)

3)But really dot understand where i install Identityserver4.Entityframework package in Northwind.Persistence     or  Northwid.identityServer project

4)Also i want to Configure swaggr token base UI Layout and LOG management in identity server

Please help me .... I really try to understand this architecture

5) Please help me to replace or configure AddInMemory to  Entity framework (database)

 services.AddIdentityServer()
                // The AddDeveloperSigningCredential extension creates temporary key material for signing tokens.
                // This might be useful to get started, but needs to be replaced by some persistent key material for production scenarios.
                // See http://docs.identityserver.io/en/release/topics/crypto.html#refcrypto for more information.
                .AddDeveloperSigningCredential()
                .AddInMemoryPersistedGrants()
                // To configure IdentityServer to use EntityFramework (EF) as the storage mechanism for configuration data (rather than using the in-memory implementations),
                // see https://identityserver4.readthedocs.io/en/release/quickstarts/8_entity_framework.html
                .AddInMemoryIdentityResources(IdentityServerConfig.GetIdentityResources())
                .AddInMemoryApiResources(IdentityServerConfig.GetApiResources())
                .AddInMemoryClients(IdentityServerConfig.GetClients())

**Comment by CodeRapp3r** [comment]
Please help ???

**Comment by CodeRapp3r** [comment]
thank you  it resolve 5 th point 

But really dot understand where i install Identityserver4.Entityframework package in Northwind.Persistence or Northwid.identityServer project

**Comment by NghiaNguyen170192** [comment]
@CodeRapp3r In order to implement IdentityServer4 and Entity Framework, I suggest you to start with the basic not to implement the code for NorthWindTrader. The basic IdentityServer implementation has 2 parts, **IdentityUser** and **IdentityRole**. You inherit the **IdentityUser** for your **YourCustomUser**.   Create new project using VisualStudio/VSCode/ your terminal. Create **YourCustomUser** class and implement:
` public class YourCustomUser : IdentityUser
    {
        public YourCustomUser() : base() { }
        public YourCustomUser(string userName) : base(userName) { }
        public YourCustomProperTy YourCustomProperTy  { get; set; }
    }`

Then, in your YourDbContext, you need to use **IdentityDbContext** instead of **DbContext**.
` public class YourDbContext : IdentityDbContext<YourCustomUser>
    {
        public YourDbContext(DbContextOptions<YourDbContext> options)
            : base(options)
        {
        }

        public DbSet<YourCustomUser> YourCustomUsers { get; set; }
      

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            //Custom model builder here
        }
    }`
Once you do this, this will use AspNetUser includes with your custom properties 
Then in your StartUp.cs
Add this code below to your **ConfigureServices**
` services.AddDbContext<YourDbContext>(options =>
                options.UseSqlServer(
                    Configuration.GetConnectionString("DefaultConnection")));
            services.AddIdentity<YourCustomUser, IdentityRole>()
                .AddRoles<IdentityRole>()
                .AddDefaultUI()
                .AddRoleManager<RoleManager<IdentityRole>>()
                .AddDefaultTokenProviders()
                .AddEntityFrameworkStores<YourDbContext>();`
Then in your **Configure** method, use
`  app.UseAuthentication();`

**Comment by CodeRapp3r** [comment]
Thank You
