### ISSUE TITLE
Rodemap Of this project

### ISSUE THREAD

**Issue by CodeRapp3r** [JasonGT/NorthwindTraders#32]
Please Add Milestone Of this project.

**Comment by CodeRapp3r** [comment]
thank you @JasonGT  . Lot Of programmer take intrest in simple .net core architecture. Your youtube video is view by more than 100k times. and if you read most of the comment.you noticed lot of  programmer want to use this architecture.  even i used this architecture in my project. But the problem is you and your team is not giving 100%  to this architecture pattern .Lot of thing is missing

1)this project is not well documented -lot confusion because this is not well documented. if i want to use dapper along with entity framework.so what can i do.
1.2)i tried to impediment identity server module in my project but i really dont know how and where.

2)Now yo add roadmap but not time span specified
3) ASP.NET Core Identity with implementing identity server  

i just want to say it i really want to used this architecture in my project. but  last one month i check this git project and nothing happening. no major chnages is reflected in this project. So please as soon as complete ASP.NET Core Identity with implementing identity server

**Comment by JasonGT** [comment]
Hi again @CodeRapp3r 

Thanks for your feedback. Some comments.

> But the problem is you and your team is not giving 100% to this architecture pattern

It's just me, no team. I have a job, family, and other commitments - I can't give 100%.

> 1)this project is not well documented -lot confusion because this is not well documented. if i want to use dapper along with entity framework.so what can i do.

I'll look at adding a GitBook in the future. There is already some use of Dapper in this project.

> 2)if i want to use SQL Server with mango db . how? and where ?

https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-2.2&tabs=visual-studio

> 1.3)i tried to impediment identity server module in my project but i really dont know how and where.

Coming soon.

> 1.4) signaler implementation how? and where ?

https://docs.microsoft.com/en-us/aspnet/core/signalr/introduction?view=aspnetcore-2.2


I can't and won't cover everything. This solution in it's current state is just there to support the topics covered in the Clean Architecture talk. While I would love to help more, I simple don't have the capacity.

All the best.

**Comment by pranavpatil19** [comment]
@JasonGT  please replay as soon as possible . it really help

where you implement Identity server 4 ? In new separate project like Northwind.identityServer or in same Api  Northwind.WebUI project .  So accordingly i want to customize my project coding implementation
Y

**Comment by JuanGarciaCarmona** [comment]
Hi,

@JasonGT , thanks for sharing this repo, it helped me a lot, it made me think and change some key aspects in my design that, well, really helped me to boost my progress in a personal project. 

@pranavpatil19 , don't get angry with me but I think you shoulnd't demmand that way, as JsonGT said this repository has general learning and teaching purposes although one can feel that is possible to create a company or a whole corporation just from here. That's not the case.

On the other hand, I'm currently creating my company and some of the code has been refactored recently to behave similar than NorthwindTraders Application Layer because I saw the video and I fell in love with Mediatr at first sight. Once said this I can give you some advices.

Starting from yopur last question Identity Server can be in the same solution but should be a separate project. I mean that regardless you can have your API and All the Identity server custom views in the same project I'd keep in a separate project but sharing some of the core libraries or at least the domain library so that your IDentityDbContext will know and manage all your identity entities and your CompanyDbContext can have its code domain entities but alse interact with Identity (to check roles or whatever other Bussines rule). In addition this will allow you to have federation and multiple clients with identity capabilities. That is pure separation of concerns, I mean, to apply SRP at software components level.

I you want to use SQL Server and Mongo DB you should have your Generic repository interface and your concrete SQLBasedRepository:IGenericRepository<T> (that's just an example) and, well, in the case of Mongo you could have also MongoBasedRepository:IGenericRepository<T> (Where T must be a document, I wrote a similar repo last year and it took me around 5 minutes to find the recipe and code it, I could sahre it if you ask me)... That is the how, I mean, none of those technolgies are new so it is quite easy to find recipes... Where? Well, there was a thread in this repo talking about if persistence layer, as is right now (or at is was, I'm not sure it changed) was against Clean Architecture principles. I had my own opinion about this nd I'll share it here. Methodologies are at our service and not the other way around, to decouple the application layer from the persistence layer can be tedious (you can think on doing some CQRS with microservices, I honestly would do that) but ASP NEt Core dependency injection worked very well for me.... And there you have your "where": Create your interfaces, for mongo and SQL, and in your command handlers you inject and use them as you decide. That's the beauty I saw with Mediatr, the versavility it adds, the extreme separation of concerns you get. you can have a method in your API that requires something from a Document Database? the your command handler references a document repo and it uses it, and the handler implementation is concise because it goes straight to the point. Am I right?

(Maybe I'm writing too much, I only wanted to help, My answers in S.O. use to be like this too, with quick examples and opinions, that's the way I think)

NOTE: I've just reviewed what I wrote and I've found that, as I thought, My MongoDbImplementation was based on the Article thaty Json Shared, using MongoDB.Bson and MongoDB.Bson.Serialization.Attributes and MongoDbGenericRepository NuGet packges:

```
public class BlablablaRepository : BaseMongoRepository, IBlablablaRepository
    {
        public BlablablaRepository(string connectionString, string databaseName) 
            : base(connectionString, databaseName)
        {
        }
    }

```
Last few words regarding SignalR: SignalR is a huge topic. The dev team has created a tremendous library with great features that are desirable to have in a lot of use cases but as the topic is huge the possibilities are huge. I've been using SignalR in many different projects during last ten years and every time I added SignalR to these projects I had to study and decide what was going to be the right approach, and that would occur today. JSon shared the best entry point to SignalR and from there the only thing that I would do is to create few Proof of concepts, in order to learn how to interact with it (i.e.: a remote console logger getting and showing every json message, a small javascript application with that chant example or, close to your real typescript application a small "chat module" that might be used or might become the seed for a real SignalR-based feature in your web app.

Again, sorry for this big bunch of messy words, I only wanted to help and, well, I'm open to help too with any question.

**Comment by pranavpatil19** [comment]
thank you very much @JuanGarciaCarmona  , i am not angry on you ...  

I like to check SQL Server and Mongo DB  Generic repository ,if you dont have any problem please share me

**Comment by JuanGarciaCarmona** [comment]
I'm just writing you an email...
