### ISSUE TITLE
Remove dependency on the DbContext in the application layer

### ISSUE THREAD

**Issue by LyonBlecher** [JasonGT/NorthwindTraders#34]
I was looking at the project last night, wish I had seen it a year ago before i started my current project at work, but was wondering if creating an interface defining the dbcontext and the methods required in the Application Layer, and then creating an implementation of this interface in your persistence layer encapsulating your actual persistence layer calls might make your application layer even more independent of your persistence layer. It does result in more code though. So for example my application layer defines that it needs a dbcontext of type IDbContext, which can be registered using dependency injection, and there is a method to add a customer, it doesnt care about the implementation just that it is guaranteed that there will be a add method. Doing this would also remove any dependency on actual ef core technologies and allow an easy change to other persistence mediums. What are your thoughts on this?

**Comment by sporifolous** [comment]
I agree. I thought it was really strange to see the DbContext implementation being passed in to the command handlers. How are you supposed to test that command handler, the most important thing to test I think because it contains all the business logic, when it requires a concrete database implementation?

**Comment by superjose** [comment]
@sporifolous
I believe it's because there's no interface for the DbContext. As you  mentioned, the DbContext is testable by itself, that's why you pass it as a concrete dependency. 


See pages 21 and 22 of his slide deck (Link in the README)
https://github.com/JasonGT/NorthwindTraders/raw/master/Slides.pdf

**Comment by petterek** [comment]
I tend to agree with @LyonBlecher that the business layer, should own the contract for it's dbLayer, and say something explicit about what it need to do what it is supposed to do :) Then the implementation of that "DbLayer" contract could take a dependency on the DBContext from EFCore.  Will increase the amount of code, but also make things more clear and testable.

**Comment by cchance27** [comment]
I was actually just coming to open an issue with this, based on the principals it would see that the application layer is breaking with the whole concept of inner layers not relying on outside layers. Pretty blatantly since the application layers have using statements for an outside layer.

**Comment by rafalschmidt97** [comment]
@LyonBlecher - it was already discussed -https://github.com/JasonGT/NorthwindTraders/issues/18

**Comment by JasonGT** [comment]
Thanks all. As mentioned this has already been discussed - #18.
