### ISSUE TITLE
Possible bug in UpdateCustomer

### ISSUE THREAD

**Issue by mjr27** [JasonGT/NorthwindTraders#69]
Looks like `id` route parameter is never used

```c#
        [HttpPut("{id}")]
        [ProducesResponseType(StatusCodes.Status204NoContent)]
        [ProducesDefaultResponseType]
        public async Task<IActionResult> Update(string id, [FromBody]UpdateCustomerCommand command)
        {
            await Mediator.Send(command);

            return NoContent();
        }
```

Actually, that's the thing i'm struggling with right now. For updates ID ususally comes from route, and all the rest comes from the body. And i got several options, in order from bad to worse:

* Make `UpdateCustomerDto` and create UpdateCustomerCommand from Dto and Id in controller -- too much boilerplate
* Validate in controller that id == command.Id -- a bit less of boilerplate, but seems wierd
* Put [FromRoute]/[FromBody] annotations in command -- it's really a wrong place for that
* Get rid of FromRoute (single endpoint for changing all records) -- not really restful.

Did i miss something?

**Comment by NerijusD** [comment]
You have one more option:
```
   command.id = id; // enforced consistency
   await Mediator.Send(command);
   return NoContent();
```

**Comment by mjr27** [comment]
This is also not that perfect -- in swagger (and more importantly, in auto-generated clients) id will appear both in route and body. 

And, what's even worse, fluentvalidation will get broken because it runs before controller is actually called.

**Comment by JasonGT** [comment]
A good question. We need the **Id** in the command, since the command needs to contain all information nececessary to update a customer. We also need the **Id** in the route, since we are building (at least trying to build) restful APIs.

I think the best approach is to handle this at the Web API level, since it is an API concern. That being the case, my recommendation is as follows:

```
            if (id != command.Id)
            {
                return BadRequest();
            }
```

At this stage, I don't think more effort is required. If this approach ends up being too painful, I'll change it later.

> And, what's even worse, fluentvalidation will get broken because it runs before controller is actually called.

Just on the above point. In this case, fluent validation only runs on the commands and queries, not the controller actions. This is a result of the following within **Startup.cs**:

```
            services.Configure<ApiBehaviorOptions>(options =>
            {
                options.SuppressModelStateInvalidFilter = true;
            });
```

And the following validation behaviour; https://github.com/JasonGT/NorthwindTraders/blob/master/Northwind.Application/Infrastructure/RequestValidationBehavior.cs.

Hope this helps.

**Comment by nixonad** [comment]
afaik, the `SuppressModelStateInvalidFilter` setting doesn't prevent the validation from running, it only stops the MVC pipeline from returning a BadRequest response when the Model is invalid.

https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.apibehavioroptions.suppressmodelstateinvalidfilter?view=aspnetcore-2.2

**Comment by DenissKulakov** [comment]
> A good question. We need the **Id** in the command, since the command needs to contain all information nececessary to update a customer. We also need the **Id** in the route, since we are building (at least trying to build) restful APIs.
> 
> I think the best approach is to handle this at the Web API level, since it is an API concern. That being the case, my recommendation is as follows:
> 
> ```
>             if (id != command.Id)
>             {
>                 return BadRequest();
>             }
> ```
> At this stage, I don't think more effort is required. If this approach ends up being too painful, I'll change it later.
> 
> > And, what's even worse, fluentvalidation will get broken because it runs before controller is actually called.
> 
> Just on the above point. In this case, fluent validation only runs on the commands and queries, not the controller actions. This is a result of the following within **Startup.cs**:
> 
> ```
>             services.Configure<ApiBehaviorOptions>(options =>
>             {
>                 options.SuppressModelStateInvalidFilter = true;
>             });
> ```
> And the following validation behaviour; https://github.com/JasonGT/NorthwindTraders/blob/master/Northwind.Application/Infrastructure/RequestValidationBehavior.cs.
> 
> Hope this helps.

I think it is not mandatory to include server generated (Id, TimeStapmps (creation date), Unique Sequential numbers) info in a PUT resource representation, if like you say _at least trying to build restful APIs_. 

The reason is that reprepresntation get from the GET request may be different from that you use in PUT request, but **it does not meant that the representation is not complete/full**. e.g. up to you to decide that concrete representation is complete/describes the resource completely. Its obvious and mandatory to include in the put representation all fields that user may/can change but not for the server side generated stuff. The RFC 7231 itself does not says that it is requred to create a new resource on a put, only to respond correctly if server actually creates a new one.

From the [RFC 7231 4.3.4 PUT](https://tools.ietf.org/html/rfc7231#section-4.3.4):

> If the target resource does not have a current representation and the
>    PUT successfully creates one, then the origin server MUST inform the
>    user agent by sending a 201 (Created) response. 

> It (_HTTP_) does not define how
>    resource state is "stored", nor how such storage might change as a
>    result of a change in resource state, nor how the origin server
>    translates resource state into representations.  Generally speaking,
>    all implementation details behind the resource interface are
>    intentionally hidden by the server.

Also the Id field is not the resource identifier in a REST. Identificator for the client is a resource url itself, location - the whole url. The Id field in this case is more like implementation details that your backend API is using internally to track entites and recognize them. But if your client using ID field for url construction (hacking urls) thats not good and should not affect your API design. This leads to a hypermedia question, but that not the case of this topic.

> An origin server SHOULD verify that the PUT representation is
>    consistent with any constraints the server has for the target
>    resource that cannot or will not be changed by the PUT.  This is
>    particularly important when the origin server uses internal
>    configuration information related to the URI in order to set the
>    values for representation metadata on GET responses. 

The [Rest CookBook](https://www.amazon.com/RESTful-Web-Services-Cookbook-Scalability-ebook/dp/B0043D2ESQ) says:

> Use PUT to create new resources only when the client can control part of the URI. For
> instance, a storage server may allocate a root URI for each client and let clients create
> new resources using that root URI as a root directory on a filesystem. Otherwise,
> use POST. 

> When you support PUT to create new resources, clients must be able to assign URIs for
> resources.

So i assume if API is not supporting creation of resources via PUT(**only replacement the contents of an existing resource, not location change**) because Id is generated on server side by ORM (EF) and client cant decide it by himself, removing the Id field from the PUT representation is ok and it will be still complete (representatino is still complete). 

There are a couple of question on a stack about it:
https://stackoverflow.com/questions/19821221/rest-api-design-of-a-resource-whose-properties-are-not-editable-by-the-client
https://stackoverflow.com/questions/36498982/same-representation-for-get-and-put
