### ISSUE TITLE
Where to put services with custom business logic

### ISSUE THREAD

**Issue by t3hInox** [JasonGT/NorthwindTraders#71]
Hi!

Currently I see that the logic which is in Northwind.Application project is very suitable for basic UI CRUD operations. Currently I am at the point in developing my application where I need to introduce custom business logic which is out of scope from basic CRUD operations (for example, I need to read, parse, process XML files) thus it is not clear to me how to handle it. This logic would belong in some sort of services, but where would an appropriate place in this template to put these service classes? How could it look like? Maybe domain layer?

Theoretically I understand that I can create a command (as per CQRS pattern), however, I feel that certain logic would be tied to that specific command even though there are parts of business logic which could be used in throughout application layer (many commands and queries).

Thanks!

**Comment by JasonGT** [comment]
Hi @t3hInox, thanks for your question.

Suggest implementing as follows:

1. Within Application, create an interface and models for working with the data.
2. Within Infrastructure, create an implementation that works with the XML files.
3. Within Application, create a query or command to work with the new interface and models.

Some key points:

- The query / command will contain the business logic. That logic will interact with the new interface to receive the data.
- The models will be contained within the Applciation layer. They will be basic data transfer objects. 
- The query / command won't know anything at all about the XML, since the implementation is contained within Infrastructure. 
- The implemntation will be responsible for reading the XML files and returning models.
- The implementation can change at anytime, and this won't affect business logic.

Hope this helps.

**Comment by t3hInox** [comment]
Thanks, @JasonGT !
Appreciate your feedback.
