### ISSUE TITLE
Question: Role check in the application layer

### ISSUE THREAD

**Issue by qazq** [JasonGT/NorthwindTraders#88]
For example, update employee information needed "master" role, delete an employee needed "admin" role. In my old design, I use role-based authorization in ASP.NET Core. I'd like to check each request permission in the application layer. How can I do? Thanks.

**Comment by rafalschmidt97** [comment]
Hi! There are planty ways to do this. For example:
1. Create IAdminRequest which extends IRequest. Then prepare pipe for mediatr which check type for requests (all extends IRequest but you can distinguish direct type) and if for example it is IAdminRequest then you can check Context and find if this request contains claims for admin.
2. Api gateway 💩 api should not care about this. Gateway can works as a guard.
3. Check roles in cqrs requests 😅
4. Keep it in controllers - simplest but not fancy at all 🙃

Good luck 🤓

**Comment by JasonGT** [comment]
Thanks @qazq , I'll include an example in #92.

Great suggestions @rafalschmidt97 - thanks.

**Comment by mihailvidishev** [comment]
My User has a role. I define for role permissions. Web controller receives some kind of model, then I instanciate

**Comment by mihailvidishev** [comment]
My User has a role. I define for role permissions.
Web controller receives some kind of model, then I create cqrs request with model and user instance and pass it to handler.
Each handler has own list of necessary permissions which I initialise in constructor, then I call method check permissions which takes user checks permissions and throws forbidden error direct in request Handle, each Handler inherits from AbstractHandler which has virtual method CheckPermissions(User user).
I has to call validation inside handler too, because of validation in pipeline forces to validate full cqrs request but I need validate only model which is in cqrs request.
I understand my design needs me to implement more boilerplate code and method calls.
My ask is to get some piece of advice for better design.
